// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCh2zr1q577cJ9uvF0bwWILMYT7gDL3TA',
    appId: '1:610671451496:web:e11df286d748df88078add',
    messagingSenderId: '610671451496',
    projectId: 'amma-food-city',
    authDomain: 'amma-food-city.firebaseapp.com',
    storageBucket: 'amma-food-city.firebasestorage.app',
    measurementId: 'G-NB6H46GE8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzC94SifvOgj8VPaW5ZsTqJP6FciFTwQ',
    appId: '1:610671451496:android:b5c88d9c02527ffa078add',
    messagingSenderId: '610671451496',
    projectId: 'amma-food-city',
    storageBucket: 'amma-food-city.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8b6aXS6UusN_lhPJCIZ8A_KLms066dqk',
    appId: '1:610671451496:ios:34755b2de8b10523078add',
    messagingSenderId: '610671451496',
    projectId: 'amma-food-city',
    storageBucket: 'amma-food-city.firebasestorage.app',
    iosBundleId: 'com.example.ammaFoodCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8b6aXS6UusN_lhPJCIZ8A_KLms066dqk',
    appId: '1:610671451496:ios:34755b2de8b10523078add',
    messagingSenderId: '610671451496',
    projectId: 'amma-food-city',
    storageBucket: 'amma-food-city.firebasestorage.app',
    iosBundleId: 'com.example.ammaFoodCity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCh2zr1q577cJ9uvF0bwWILMYT7gDL3TA',
    appId: '1:610671451496:web:9706519b6adc6dd4078add',
    messagingSenderId: '610671451496',
    projectId: 'amma-food-city',
    authDomain: 'amma-food-city.firebaseapp.com',
    storageBucket: 'amma-food-city.firebasestorage.app',
    measurementId: 'G-8ZPYBQBVDR',
  );

}